name: 'testgen_demo'
version: '0.1'
config-version: 2

profile: 'integration_tests'

test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
